### ISSUE TITLE
firefox audio problem

### ISSUE THREAD

**Issue by miki10194** [wmik/use-media-recorder#10]
When I set 
`mediaStreamConstraints: { audio: false, video: true }` below listener (inside your hook) is not called and doesn't return blob me
`mediaRecorder.current.addEventListener('stop', handleStop);`
@wmik  Do you know what can cause this?

**Comment by wmik** [comment]
Hi @miki10194 
Not entirely sure what could be causing the issue unfortunately.

A few quick questions to help debug this:

- Does your code produce/report/throw any errors?
- What are the results of the error object returned by the hook?
- Would you mind sharing some sample code?

**Comment by miki10194** [comment]
@wmik 
1) no
2) there is no errors, only doesn't return blob after stopRecording
3) I think, the best solution will be when you can use your hook in simple example
`  const {
    status,
    mediaBlob,
    liveStream,
    stopRecording,
    startRecording,
    clearMediaStream,
    unMuteAudio,
    muteAudio,
    isAudioMuted,
    getMediaStream,
    pauseRecording,
    resumeRecording,
  } = useMediaRecorder({
    recordScreen: true,
    blobOptions: { type: 'video/webm' },
    mediaStreamConstraints: {
      audio: false,
      video: true,
    },
    mediaRecorderOptions: {
      mimeType: (window as any).MediaRecorder?.isTypeSupported('video/webm;codecs=vp9,opus')
        ? 'video/webm;codecs=vp9,opus'
        : 'video/webm;codecs=vp8,opus',
    },
  });`
  add button startRecording/stopRecording and check yourself

**Comment by miki10194** [comment]
@wmik 
I think we can close this issue, because I had set always `mediaRecorderOptions: { mimeType: 'video/webm;codecs=vp8,opus' }`
For firefox when audio is false and audio codec `opus` is set in mimeType it causes some internal problems :D
