### ISSUE TITLE
capture custom stream

### ISSUE THREAD

**Issue by no-1ne** [wmik/use-media-recorder#13]
Thank you for sharing your work, would you consider recording from a custom stream like this https://github.com/0x006F/react-media-recorder/pull/24

**Comment by wmik** [comment]
Hi @startupgurukul 
I appreciate that and thank you for checking it out
Sure I believe we can 😄 
Feel free to open a pull request 🤝

**Comment by startupgurukul** [comment]
Created a pull request while on the move as its a small change..pardon any mistakes

https://github.com/wmik/use-media-recorder/pull/14
https://github.com/wmik/use-media-recorder/pull/15

**Comment by wmik** [comment]
Supported in version 1.3.0-beta.0
