### ISSUE TITLE
Corrupted Downloaded File

### ISSUE THREAD

**Issue by alirazachishti** [wmik/use-media-recorder#2]
I am creating audio blob using this code
```
const {
    error,
    status,
    mediaBlob,
    stopRecording,
    getMediaStream,
    startRecording,
    pauseRecording,
    resumeRecording,
  } = useMediaRecorder({
    recordScreen: false,
    blobOptions: { type: 'audio/wav' },
    mediaStreamConstraints: { audio: true },
  });
```
But when I download the blob after calling method **onStop**, it downloads a corrupted file.
Although it is audible but it does not contain proper formatting
![image](https://user-images.githubusercontent.com/25838209/87559758-24251d80-c6d4-11ea-983b-221eb9650603.png)

Anyone plz guide me related to this issue
Thanks

**Comment by wmik** [comment]
Hi @alichishiti I believe that's an error in formatting.
I doubt web audio can be recorded in wav format so I now realize how the example can be misleading.
Try using a supported format such as `audio/webm` then convert into the desired format.
Here's a [list of supported media types](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/isTypeSupported)
Hope that helps

**Comment by alichishiti** [comment]
Than you so much for you reply @wmik 
I changed the audio format which is supported according to the link you provided as you can see below
```
    resumeRecording,
  } = useMediaRecorder({
    recordScreen: false,
    blobOptions: { type: 'audio/webm' },
    mediaStreamConstraints: { audio: true },
```
and then I downloaded the .webm file but still it does not have length attribute as we can see in a proper audio file details (see the second box) 

![image](https://user-images.githubusercontent.com/25838209/89667929-6d911300-d8f6-11ea-8e78-d80f830eff8f.png)
I shall be highly thankful if you guide me related to this issue
Thanks

**Comment by wmik** [comment]
Oh I see!
Sadly @alichishiti this is a bug in most browsers that's been around for a while:

- [Chrome webm issue/bug](https://bugs.chromium.org/p/chromium/issues/detail?id=642012)
- [Firefox webm issue](https://bugzilla.mozilla.org/show_bug.cgi?id=969290)

For some reason the length/duration is not properly written into the file headers with webm.
Although once you convert the audio file into a different format e.g `mp3/wav` the length attribute will show up.
Hope that helps

**Comment by alichishiti** [comment]
Thank you so much @wmik  for reply
I tried your suggestion,
I recorded in .webm format
 ```
 } = useMediaRecorder({
    recordScreen: false,
    blobOptions: { type: 'audio/webm' },
    mediaStreamConstraints: { audio: true },
  });
```
and then save it in wav format, it even removes the bitrate, audio sample rate from the details, here are screenshots for them
![image](https://user-images.githubusercontent.com/25838209/89757504-e2cf3480-dafe-11ea-9bb0-a11e7c694738.png)

**Comment by wmik** [comment]
Hi @alichishiti 
Unfortunately changing the filename does not necessarily encode the file into the desired format.
Try using an online converter or a library such as ffmpeg to convert to different formats since audio conversion is more or less data encoding and decoding.
