### ISSUE TITLE
handleStop errors if there are no chunks

### ISSUE THREAD

**Issue by swissspidy** [wmik/use-media-recorder#26]
Affected code:

https://github.com/wmik/use-media-recorder/blob/9660bb10376bfd9e9052966d706d44450508d657/index.js#L187-L198

When `mediaChunks.current` is an empty array, `sampleChunk` will be `undefined` and so accessing `sampleChunk.type` throws an error.

**Comment by wmik** [comment]
Attempted patch in v1.6.2-beta.0
Feel free to close this if it works as intended

**Comment by swissspidy** [comment]
Looks like that did the trick, thank you!
