### ISSUE TITLE
Errors from `MediaRecorder.start()` not caught

### ISSUE THREAD

**Issue by swissspidy** [wmik/use-media-recorder#29]
Citing [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/start#exceptions):

> Errors that can be detected immediately are thrown as DOM exceptions. All other errors are reported through [`error`](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/error_event) events sent to the `MediaRecorder` object. You can implement the [`onerror`](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/error_event) event handler to respond to these errors.

The former (thrown DOM exceptions) are not currently caught here:

https://github.com/wmik/use-media-recorder/blob/766484cf71646c0c53f1231f53cba786b83560bb/index.js#L172-L176

Something like this should fix it:

```diff
      mediaRecorder.current.addEventListener('stop', handleStop);
      mediaRecorder.current.addEventListener('error', handleError);
-     mediaRecorder.current.start(timeSlice);
-     setStatus('recording');
-     onStart();
+     try {
+       mediaRecorder.current.start(timeSlice);
+       setStatus('recording');
+       onStart();
+     } catch (error) {
+       handleError({ error });
+     }
```

**Comment by wmik** [comment]
Nice catch @swissspidy 🤝 
Patched in version 1.6.4-beta.0
