### ISSUE TITLE
stopRecording() not change status to stopped when mediaChunks.current not available

### ISSUE THREAD

**Issue by kedangghet** [wmik/use-media-recorder#30]
https://github.com/wmik/use-media-recorder/blob/766484cf71646c0c53f1231f53cba786b83560bb/index.js#L187-L206

I think move `setStatus('stopped');` to line 204, before call   ` onStop(blob);`

**Comment by wmik** [comment]
Nice catch @kedangghet  🤝 
Patched in version 1.6.4-beta.0
